---
# Firewall configuration tasks

- name: Install firewalld
  dnf:
    name: firewalld
    state: present

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Set default zone
  firewalld:
    default_zone: public
    state: enabled
    permanent: yes

- name: Set default policies
  firewalld:
    zone: public
    target: "{{ firewall_default_policy }}"
    permanent: yes
    state: enabled

- name: Configure allowed ports
  firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: yes
    state: enabled
    zone: public
  with_items: "{{ firewall_allowed_ports }}"
  notify: reload firewall

- name: Enable logging for dropped packets
  firewalld:
    rich_rule: 'rule family="ipv4" log prefix="firewalld-dropped: " level="warning" limit value="5/m" drop'
    permanent: yes
    state: enabled
    zone: public
  notify: reload firewall

- name: Configure rate limiting for SSH
  firewalld:
    rich_rule: 'rule service name="ssh" limit value="10/m" accept'
    permanent: yes
    state: enabled
    zone: public
  notify: reload firewall

- name: Block common attack ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: disabled
    zone: public
  with_items:
    - 23/tcp    # Telnet
    - 21/tcp    # FTP
    - 161/udp   # SNMP
    - 445/tcp   # SMB
    - 137/udp   # NetBIOS
    - 138/udp   # NetBIOS
    - 139/tcp   # NetBIOS
  notify: reload firewall

- name: Configure connection tracking
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: 'net.netfilter.nf_conntrack_max', value: '131072' }
    - { key: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '86400' }
    - { key: 'net.netfilter.nf_conntrack_tcp_timeout_close_wait', value: '60' }
  notify: reload sysctl 